sudo: required

services:
  - docker

before_install:
  - docker build -t rwhughes91/multi-client-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true rwhughes91/multi-client-test:latest npm test

after_success:
  - docker build -t rwhughes91/multi-client ./client
  - docker build -t rwhughes91/multi-nginx ./nginx
  - docker build -t rwhughes91/multi-api ./server
  - docker build -t rwhughes91/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take these images and push them to Docker Hub
  - docker push rwhughes91/multi-client
  - docker push rwhughes91/multi-nginx
  - docker push rwhughes91/multi-api
  - docker push rwhughes91/multi-worker

deploy:
  provider: elasticbeanstalk
  region: 'us-east-1'
  app: 'multi-docker'
  env: 'MultiDocker-env'
  bucket_name: 'elasticbeanstalk-us-east-1-923445559289'
  bucket_path: 'docker-multi'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
